import type { Locale } from "@/lib/dictionary";

export const pageCopy = {
  en: {
    skip: "Skip to content",
    privacy: {
      meta: "What this site measures, what it deliberately doesn't, and how long anything is kept.",
      eyebrow: "Privacy",
      title: "What this site measures",
      intro:
        "I count visits so I know whether anyone reads this. There is no advertising, no profiling, and nothing is shared with anyone.",
      cookiesTitle: "No cookies, no tracking across sites",
      cookies:
        "This site sets no cookies for analytics and stores nothing on your device. Nothing here follows you to other websites, and your visit is never combined with data from anywhere else.",
      adminCookie:
        "The one cookie the site can set is for the private admin dashboard, and only for me when I sign in.",
      recordedTitle: "What is recorded",
      recordedLead:
        "For each page view, the server records only aggregate counters:",
      recorded: [
        "the page path (for example, /projects)",
        "the referring site's hostname (for example, google.com), never the full URL or search terms",
        "country and timezone, derived on the server from the connection rather than read from your device",
        "a pseudonymous visitor ID, explained below",
      ],
      ipTitle: "Your IP address is never stored",
      ip: "To distinguish visitors without identifying them, the server makes a one-way SHA-256 hash of your IP address and browser user-agent, combined with a secret salt. Only the hash is stored; the IP address itself is never stored, logged, or retained.",
      salt: "The salt changes each calendar month and expires with it. After that, even I cannot recompute the hashes or link visitors across months. The dashboard therefore reports visitor figures within the current month.",
      retentionTitle: "Retention",
      retention:
        "Aggregate counters are kept for at most 400 days and expire automatically. There is no raw event log or per-visit history, only totals.",
      botsTitle: "Automated traffic",
      bots: "Crawlers and bots are filtered out before anything is recorded, so the counts reflect people rather than machines.",
      contactTitle: "Questions, or want your data removed?",
      contact:
        "Nothing stored can be traced back to an individual, so there is no record of you to look up or delete. If you have a question, email me at",
    },
    notFound: {
      eyebrow: "Error 404",
      title: "Page not found",
      body: "The page you're looking for doesn't exist or has moved.",
      home: "Back home",
    },
    error: {
      eyebrow: "Something went wrong",
      title: "An unexpected error occurred",
      body: "Sorry about that. You can try again, or head back home.",
      retry: "Try again",
      home: "Back home",
    },
    admin: {
      meta: "Admin",
      setup: "Set ADMIN_PASSWORD in your environment to enable this page.",
      eyebrow: "Analytics",
      title: "Site traffic",
      signOut: "Sign out",
      disconnected: "Analytics isn't connected yet",
      disconnectedBody:
        "Add Upstash Redis to this Vercel project and redeploy. Until then the site keeps working; visit recording stays inactive without UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN.",
      loginTitle: "Admin",
      loginIntro: "Enter the password to view site analytics.",
      password: "Admin password",
      checking: "Checking…",
      signIn: "Sign in",
      rate: "Too many attempts. Wait a few minutes.",
      missingPassword: "ADMIN_PASSWORD isn't set on the server.",
      wrongPassword: "Wrong password.",
      network: "Couldn't reach the server.",
      datastore: "Couldn't reach the datastore",
      datastoreBody:
        "Upstash didn't respond. The service may be temporarily unavailable or out of free commands. Visitor-side recording is unaffected; this page will update when Redis responds again.",
      viewsDay: "Views per day",
      when: "When people visit · their local time",
      busiest: "busiest around",
      views: "views",
      unique: "unique",
      days: "days",
      pageViews: "Page views",
      pageViewsHint: "Every view, with bots filtered out",
      visitors: "Visitors · month",
      visitorsHint: "Distinct visitors this month",
      returned: "Came back",
      returnedHint: "of visitors returned at least once",
      perVisitor: "Views per visitor",
      perVisitorHint: "How much of the site people read",
      cities: "Cities",
      countries: "Countries",
      pages: "Top pages",
      referrers: "Referrers",
      timezones: "Timezones",
      devices: "Devices",
      browsers: "Browsers",
      noVisits: "No visits recorded yet.",
      unknown: "Unknown",
      note: "Only aggregate counts are stored. Analytics uses no cookies, and raw IP addresses are never stored. A visitor ID is a salted SHA-256 hash of IP and browser information. The salt expires each month, so visitor and return counts only cover the current month.",
    },
  },
  fa: {
    skip: "برو به محتوای اصلی",
    privacy: {
      meta: "این سایت چه اطلاعاتی از بازدیدها نگه می‌داره و تا کی؟",
      eyebrow: "حریم خصوصی",
      title: "این سایت از بازدیدها چی می‌فهمه؟",
      intro:
        "تعداد بازدیدها رو می‌شمرم تا بدونم کسی سایت رو می‌خونه یا نه. تبلیغ و پروفایل‌سازی در کار نیست و اطلاعاتی هم به کسی داده نمی‌شه.",
      cookiesTitle: "بدون cookie تحلیلی یا ردیابی بین سایت‌ها",
      cookies:
        "برای آمار بازدیدها cookie نمی‌ذارم و چیزی روی دستگاهت ذخیره نمی‌کنم. این سایت تو رو در سایت‌های دیگه دنبال نمی‌کنه و بازدیدت رو با دادهٔ جای دیگه کنار هم نمی‌ذاره.",
      adminCookie:
        "تنها cookie احتمالی برای صفحهٔ مدیریت خودمه؛ اون هم فقط وقتی خودم واردش می‌شم.",
      recordedTitle: "چه چیزهایی ثبت می‌شن؟",
      recordedLead:
        "برای هر بازدید از صفحه، سرور فقط چند شمارندهٔ کلی ثبت می‌کنه:",
      recorded: [
        "مسیر صفحه، مثلاً /projects",
        "نام سایت ارجاع‌دهنده، مثلاً google.com؛ آدرس کامل یا عبارت جست‌وجو ثبت نمی‌شه",
        "کشور و منطقهٔ زمانی که سرور از اتصال تشخیص می‌ده؛ از دستگاهت خوانده نمی‌شن",
        "یک شناسهٔ ناشناس برای بازدیدکننده که پایین توضیحش دادم",
      ],
      ipTitle: "آدرس IP ذخیره نمی‌شه",
      ip: "برای اینکه بشه بازدیدهای یک نفر رو شمرد، سرور از IP و اطلاعات مرورگرش همراه با یک مقدار محرمانه، یک hash یک‌طرفه با SHA-256 می‌سازه. فقط همون hash ذخیره می‌شه؛ خود IP نه ذخیره می‌شه، نه توی log می‌مونه.",
      salt: "اون مقدار محرمانه هر ماه عوض می‌شه و قبلی از بین می‌ره. بعد از اون حتی خودم هم نمی‌تونم hashهای ماه قبل رو دوباره بسازم یا بازدیدهای چند ماه رو به هم وصل کنم. برای همین آمار بازدیدکننده‌های داشبورد فقط مربوط به ماه جاریه.",
      retentionTitle: "اطلاعات تا کی می‌مونن؟",
      retention:
        "شمارنده‌های کلی حداکثر ۴۰۰ روز می‌مونن و بعد خودکار حذف می‌شن. تاریخچهٔ تک‌تک بازدیدها یا log خامی نگه داشته نمی‌شه.",
      botsTitle: "بازدید ربات‌ها",
      bots: "بازدید ربات‌ها و خزنده‌ها قبل از ثبت آمار کنار گذاشته می‌شه تا عددها بیشتر بازدید آدم‌ها رو نشون بدن.",
      contactTitle: "سؤال داری؟",
      contact:
        "چون اطلاعات ذخیره‌شده به یک نفر مشخص وصل نمی‌شن، سابقه‌ای از بازدید تو ندارم که پیداش کنم یا پاکش کنم. اگه سؤالی داری، به این آدرس ایمیل بزن:",
    },
    notFound: {
      eyebrow: "خطای ۴۰۴",
      title: "این صفحه پیدا نشد",
      body: "ممکنه آدرسش عوض شده باشه یا دیگه وجود نداشته باشه.",
      home: "برگشت به خانه",
    },
    error: {
      eyebrow: "یه مشکلی پیش اومد",
      title: "صفحه درست باز نشد",
      body: "یه بار دیگه امتحان کن. اگه باز هم نشد، برگرد به صفحهٔ اصلی.",
      retry: "تلاش دوباره",
      home: "برگشت به خانه",
    },
    admin: {
      meta: "مدیریت",
      setup: "برای فعال شدن این صفحه، ADMIN_PASSWORD رو توی تنظیمات سرور بذار.",
      eyebrow: "آمار سایت",
      title: "بازدیدهای سایت",
      signOut: "خروج",
      disconnected: "آمار سایت هنوز وصل نیست",
      disconnectedBody:
        "Upstash Redis رو به پروژهٔ Vercel وصل کن و دوباره deploy بگیر. سایت همچنان کار می‌کنه؛ بدون UPSTASH_REDIS_REST_URL و UPSTASH_REDIS_REST_TOKEN فقط آمار بازدید ثبت نمی‌شه.",
      loginTitle: "مدیریت سایت",
      loginIntro: "برای دیدن آمار سایت، رمز رو وارد کن.",
      password: "رمز مدیریت",
      checking: "دارم بررسی می‌کنم…",
      signIn: "ورود",
      rate: "تلاش‌ها زیاد شد. چند دقیقه دیگه دوباره امتحان کن.",
      missingPassword: "ADMIN_PASSWORD روی سرور تنظیم نشده.",
      wrongPassword: "رمز اشتباهه.",
      network: "ارتباط با سرور برقرار نشد.",
      datastore: "ارتباط با محل ذخیرهٔ آمار برقرار نشد",
      datastoreBody:
        "Upstash جواب نداد؛ شاید مشکل موقتی باشه یا سهمیهٔ رایگان تموم شده باشه. ثبت بازدیدهای سایت ادامه داره و این صفحه بعد از وصل شدن Redis دوباره پر می‌شه.",
      viewsDay: "بازدید در هر روز",
      when: "زمان بازدید · به وقت خود بازدیدکننده‌ها",
      busiest: "شلوغ‌ترین ساعت: حدود",
      views: "بازدید",
      unique: "بازدیدکننده",
      days: "روز",
      pageViews: "بازدید صفحه",
      pageViewsHint: "همهٔ بازدیدها، بدون ربات‌ها",
      visitors: "بازدیدکننده · این ماه",
      visitorsHint: "آدم‌های جداگانه‌ای که این ماه اومدن",
      returned: "دوباره برگشتن",
      returnedHint: "از بازدیدکننده‌ها حداقل یک بار برگشتن",
      perVisitor: "صفحه برای هر نفر",
      perVisitorHint: "هر نفر چند صفحه رو دیده",
      cities: "شهرها",
      countries: "کشورها",
      pages: "صفحه‌های پربازدید",
      referrers: "منابع ورودی",
      timezones: "منطقه‌های زمانی",
      devices: "دستگاه‌ها",
      browsers: "مرورگرها",
      noVisits: "هنوز بازدیدی ثبت نشده.",
      unknown: "نامشخص",
      note: "فقط شمارنده‌های کلی ذخیره می‌شن. برای آمار cookie نداریم و IP خام هم نگه نمی‌داریم. شناسهٔ بازدیدکننده از hash یک‌طرفهٔ IP و اطلاعات مرورگر ساخته می‌شه. مقدار محرمانهٔ این hash هر ماه عوض می‌شه؛ بنابراین آمار بازدیدکننده و برگشت دوباره فقط برای ماه جاریه.",
    },
  },
} as const;

export type PageCopy = (typeof pageCopy)[Locale];
