import type { Locale } from "@/lib/dictionary";
import { site } from "@/lib/site";

export const pageCopy = {
  en: {
    skip: "Skip to content",
    home: {
      title: `${site.name} — ${site.role}`,
      description:
        "Python backend & AI/LLM engineer. Resilient backend services, multi-provider LLM apps, and RAG. Ask my AI assistant anything about my work.",
    },
    projects: {
      title: "Projects",
      description:
        "Open-source projects and two workplace agents by Sina Amareh, with the problems, workflows, and engineering decisions behind them.",
    },
    privacy: {
      meta: "What this site measures, what it deliberately doesn't, and how long anything is kept.",
      eyebrow: "Privacy",
      title: "What this site measures",
      intro:
        "I count visits so I know whether anyone reads this. There is no advertising, no profiling, and nothing is shared with anyone.",
      cookiesTitle: "No analytics cookies, no tracking across sites",
      cookies:
        "Analytics sets no cookies and stores nothing on your device. Nothing here follows you to other websites, and your visit is never combined with data from anywhere else.",
      preferences:
        "A few things stay on your device, and only once you use them. Picking a language with the EN / فا switch sets a cookie named locale for one year, so the site opens in that language next time. Your theme choice is kept in your browser's storage, and an open chat with the assistant until you close the tab. None of this is used for analytics.",
      adminCookie:
        "The only other cookie is for the private admin dashboard, and only for me when I sign in.",
      recordedTitle: "What is recorded",
      recordedLead: "For each page view, the server records only aggregate counters:",
      recorded: [
        "the page path (for example, /projects)",
        "the referring site's hostname (for example, google.com), never the full URL or search terms",
        "country and timezone, derived on the server from the connection rather than read from your device",
        "a pseudonymous visitor ID, explained below",
      ],
      ipTitle: "Your IP address is never stored",
      ip: "To distinguish visitors without identifying them, the server makes a one-way SHA-256 hash of your IP address and browser user-agent, combined with a secret salt. Only the hash is stored; the IP address itself is never stored, logged, or retained.",
      salt: "The salt changes each calendar month and expires with it. After that, even I cannot recompute the hashes or link visitors across months. The dashboard therefore reports visitor figures within the current month.",
      retentionTitle: "Retention",
      retention:
        "Aggregate counters are kept for at most 400 days and expire automatically. There is no raw event log or per-visit history, only totals.",
      botsTitle: "Automated traffic",
      bots: "Crawlers and bots are filtered out before anything is recorded, so the counts reflect people rather than machines.",
      contactTitle: "Questions, or want your data removed?",
      contact:
        "Nothing stored can be traced back to an individual, so there is no record of you to look up or delete. If you have a question, email me at",
    },
    notFound: {
      eyebrow: "Error 404",
      title: "Page not found",
      body: "The page you're looking for doesn't exist or has moved.",
      home: "Back home",
    },
    error: {
      eyebrow: "Something went wrong",
      title: "An unexpected error occurred",
      body: "Sorry about that. You can try again, or head back home.",
      retry: "Try again",
      home: "Back home",
    },
    admin: {
      meta: "Admin",
      setup: "Set ADMIN_PASSWORD in your environment to enable this page.",
      eyebrow: "Analytics",
      title: "Site traffic",
      signOut: "Sign out",
      disconnected: "Analytics isn't connected yet",
      disconnectedBody:
        "Add Upstash Redis to this Vercel project and redeploy. Until then the site keeps working; visit recording stays inactive without UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN.",
      loginTitle: "Admin",
      loginIntro: "Enter the password to view site analytics.",
      password: "Admin password",
      checking: "Checking…",
      signIn: "Sign in",
      rate: "Too many attempts. Wait a few minutes.",
      missingPassword: "ADMIN_PASSWORD isn't set on the server.",
      wrongPassword: "Wrong password.",
      network: "Couldn't reach the server.",
      serverError: "Something went wrong on the server. Try again in a minute.",
      datastore: "Couldn't reach the datastore",
      datastoreBody:
        "Upstash didn't respond. The service may be temporarily unavailable or out of free commands. Visitor-side recording is unaffected; this page will update when Redis responds again.",
      days: "days",
      since: "Visit data since",
      noData: "No visits recorded yet.",
      kpi: {
        engaged: "Engaged visits",
        engagedHint: "of all visits · 10 s+ active, 2+ pages or a key action",
        visits: "All visits",
        visitsHint: "Page views under 30 min apart are one visit",
        visitors: "Visitors · this month",
        visitorsHint: "Distinct people this calendar month",
        returning: "Returning · this month",
        returningHint: "Visitors with 2+ visits this month",
        avgTime: "Avg active time",
        avgTimeHint: "Per engaged visit; idle and hidden-tab time don't count",
        pagesPerVisit: "Pages per visit",
        pagesPerVisitHint: "Page views ÷ visits, same days",
        chat: "Chat questions",
        chatHint: "Asked to the assistant",
        contact: "Contact messages",
        contactHint: "Sent through the form",
      },
      trend: "Visits per day",
      allVisits: "All visits",
      engaged: "Engaged",
      peak: "Peak",
      pageviews: "page views in this range",
      timeTitle: "Active time per visit",
      buckets: ["under 10 s", "10–30 s", "30 s – 1 min", "1–3 min", "3–10 min", "10 min+"],
      pagesTitle: "Pages by avg active time",
      views: "views",
      sectionsTitle: "How far visits get",
      sectionsHint:
        "Reach = share of the visits that opened the page and had the section on screen for about a second. Avg = how long it was the main thing on screen.",
      homeSections: "Home page",
      otherSections: "Other pages",
      sectionNames: {
        hero: "Hero · chat",
        featured: "Featured projects",
        workplace: "Workplace agents",
        about: "About",
        contact: "Contact",
        "projects-list": "Projects list",
        "workplace-detail": "Workplace agents in full",
        "case-study": "Case studies",
      },
      avg: "avg",
      doTitle: "What visitors did",
      chatAsked: "Chat questions",
      chip: "Suggested question",
      typed: "Typed question",
      outcomesTitle: "Chat outcomes",
      outcomes: {
        answered: "Answered",
        cached: "Answered from cache",
        refused: "Declined as off-topic or abusive",
        smalltalk: "Small talk",
        capped: "Daily limit reached",
        error: "Failed",
      },
      topicsTitle: "Chat topics",
      actionsTitle: "Actions",
      events: {
        chat_ask: "Chat question",
        contact_submit: "Contact message",
        resume_download: "Résumé download",
        outbound: "Outbound link",
        gallery_open: "Gallery opened",
        palette_open: "Command palette",
        lang_switch: "Language switch",
      },
      outboundTitle: "Outbound links",
      targets: {
        github: "GitHub profile",
        repo: "Project repo",
        linkedin: "LinkedIn",
        email: "Email",
        telegram: "Telegram",
      },
      acqTitle: "Where visits come from",
      acqHint: "Counted once per visit. Stored per calendar month, so these cover whole months:",
      sources: "Sources",
      entryPages: "Entry pages",
      countries: "Countries",
      cities: "Cities",
      devices: "Devices",
      browsers: "Browsers",
      languages: "Language",
      langNames: { en: "English", fa: "Persian" },
      direct: "Direct",
      deviceNames: { Desktop: "Desktop", Mobile: "Mobile", Tablet: "Tablet" },
      when: "When people visit · their local time",
      busiest: "busiest around",
      weekdays: {
        Mon: "Mon",
        Tue: "Tue",
        Wed: "Wed",
        Thu: "Thu",
        Fri: "Fri",
        Sat: "Sat",
        Sun: "Sun",
      },
      recentTitle: "Recent visits",
      recentHint: "Last 50, newest first",
      newVisitor: "New",
      returningVisitor: "Returning",
      engagedBadge: "Engaged",
      active: "active",
      sec: "s",
      min: "m",
      unknown: "Unknown",
      note: "No visitor cookies and no raw IP addresses. A visitor ID is a salted SHA-256 hash of IP and browser information; the salt expires each month, so visitor and returning counts only cover the current month. Visit records are kept for 90 days.",
    },
  },
  fa: {
    skip: "برو به محتوای اصلی",
    home: {
      title: "سینا عماره — توسعه‌دهندهٔ بک‌اند و AI",
      description:
        "من سینا عماره‌ام؛ با Python بک‌اند و برنامه‌های AI می‌سازم. از پروژه‌ها و تجربه‌هام از دستیار سایت بپرس.",
    },
    projects: {
      title: "پروژه‌ها",
      description:
        "پروژه‌های متن‌باز و دو ایجنت کاری سینا عماره؛ با توضیح مسئله، مسیر کار و تصمیم‌های فنی.",
    },
    privacy: {
      meta: "این سایت چه اطلاعاتی از بازدیدها نگه می‌داره و تا کی؟",
      eyebrow: "حریم خصوصی",
      title: "این سایت از بازدیدها چی می‌فهمه؟",
      intro:
        "تعداد بازدیدها رو می‌شمرم تا بدونم کسی سایت رو می‌خونه یا نه. تبلیغ و پروفایل‌سازی در کار نیست و اطلاعاتی هم به کسی داده نمی‌شه.",
      cookiesTitle: "بدون cookie تحلیلی یا ردیابی بین سایت‌ها",
      cookies:
        "برای آمار بازدیدها cookie نمی‌ذارم و چیزی روی دستگاهت ذخیره نمی‌کنم. این سایت تو رو در سایت‌های دیگه دنبال نمی‌کنه و بازدیدت رو با دادهٔ جای دیگه کنار هم نمی‌ذاره.",
      preferences:
        "چند چیز روی دستگاهت می‌مونه، اون هم فقط وقتی ازشون استفاده کنی. اگه با دکمهٔ EN / فا زبان رو انتخاب کنی، یک cookie به اسم locale برای یک سال ذخیره می‌شه تا دفعهٔ بعد سایت با همون زبان باز بشه. تمی که انتخاب می‌کنی توی حافظهٔ مرورگرت می‌مونه، و گفت‌وگوت با دستیار هم تا وقتی تب رو ببندی. هیچ‌کدوم از این‌ها برای آمار استفاده نمی‌شن.",
      adminCookie: "تنها cookie دیگه برای صفحهٔ مدیریت خودمه؛ اون هم فقط وقتی خودم واردش می‌شم.",
      recordedTitle: "چه چیزهایی ثبت می‌شن؟",
      recordedLead: "برای هر بازدید از صفحه، سرور فقط چند شمارندهٔ کلی ثبت می‌کنه:",
      recorded: [
        "مسیر صفحه، مثلاً /projects",
        "نام سایت ارجاع‌دهنده، مثلاً google.com؛ آدرس کامل یا عبارت جست‌وجو ثبت نمی‌شه",
        "کشور و منطقهٔ زمانی که سرور از اتصال تشخیص می‌ده؛ از دستگاهت خوانده نمی‌شن",
        "یک شناسهٔ ناشناس برای بازدیدکننده که پایین توضیحش دادم",
      ],
      ipTitle: "آدرس IP ذخیره نمی‌شه",
      ip: "برای اینکه بشه بازدیدهای یک نفر رو شمرد، سرور از IP و اطلاعات مرورگرش همراه با یک مقدار محرمانه، یک hash یک‌طرفه با SHA-256 می‌سازه. فقط همون hash ذخیره می‌شه؛ خود IP نه ذخیره می‌شه، نه توی log می‌مونه.",
      salt: "اون مقدار محرمانه هر ماه عوض می‌شه و قبلی از بین می‌ره. بعد از اون حتی خودم هم نمی‌تونم hashهای ماه قبل رو دوباره بسازم یا بازدیدهای چند ماه رو به هم وصل کنم. برای همین آمار بازدیدکننده‌های داشبورد فقط مربوط به ماه جاریه.",
      retentionTitle: "اطلاعات تا کی می‌مونن؟",
      retention:
        "شمارنده‌های کلی حداکثر ۴۰۰ روز می‌مونن و بعد خودکار حذف می‌شن. تاریخچهٔ تک‌تک بازدیدها یا log خامی نگه داشته نمی‌شه.",
      botsTitle: "بازدید ربات‌ها",
      bots: "بازدید ربات‌ها و خزنده‌ها قبل از ثبت آمار کنار گذاشته می‌شه تا عددها بیشتر بازدید آدم‌ها رو نشون بدن.",
      contactTitle: "سؤال داری؟",
      contact:
        "چون اطلاعات ذخیره‌شده به یک نفر مشخص وصل نمی‌شن، سابقه‌ای از بازدید تو ندارم که پیداش کنم یا پاکش کنم. اگه سؤالی داری، به این آدرس ایمیل بزن:",
    },
    notFound: {
      eyebrow: "خطای ۴۰۴",
      title: "این صفحه پیدا نشد",
      body: "ممکنه آدرسش عوض شده باشه یا دیگه وجود نداشته باشه.",
      home: "برگشت به خانه",
    },
    error: {
      eyebrow: "یه مشکلی پیش اومد",
      title: "صفحه درست باز نشد",
      body: "یه بار دیگه امتحان کن. اگه باز هم نشد، برگرد به صفحهٔ اصلی.",
      retry: "تلاش دوباره",
      home: "برگشت به خانه",
    },
    admin: {
      meta: "مدیریت",
      setup: "برای فعال شدن این صفحه، ADMIN_PASSWORD رو توی تنظیمات سرور بذار.",
      eyebrow: "آمار سایت",
      title: "بازدیدهای سایت",
      signOut: "خروج",
      disconnected: "آمار سایت هنوز وصل نیست",
      disconnectedBody:
        "Upstash Redis رو به پروژهٔ Vercel وصل کن و دوباره deploy بگیر. سایت همچنان کار می‌کنه؛ بدون UPSTASH_REDIS_REST_URL و UPSTASH_REDIS_REST_TOKEN فقط آمار بازدید ثبت نمی‌شه.",
      loginTitle: "مدیریت سایت",
      loginIntro: "برای دیدن آمار سایت، رمز رو وارد کن.",
      password: "رمز مدیریت",
      checking: "دارم بررسی می‌کنم…",
      signIn: "ورود",
      rate: "تلاش‌ها زیاد شد. چند دقیقه دیگه دوباره امتحان کن.",
      missingPassword: "ADMIN_PASSWORD روی سرور تنظیم نشده.",
      wrongPassword: "رمز اشتباهه.",
      network: "ارتباط با سرور برقرار نشد.",
      serverError: "سرور به مشکل خورد. یه دقیقه دیگه دوباره امتحان کن.",
      datastore: "ارتباط با محل ذخیرهٔ آمار برقرار نشد",
      datastoreBody:
        "Upstash جواب نداد؛ شاید مشکل موقتی باشه یا سهمیهٔ رایگان تموم شده باشه. ثبت بازدیدهای سایت ادامه داره و این صفحه بعد از وصل شدن Redis دوباره پر می‌شه.",
      days: "روز",
      since: "آمار بازدیدها از",
      noData: "هنوز بازدیدی ثبت نشده.",
      kpi: {
        engaged: "بازدیدهای با تعامل",
        engagedHint: "از کل بازدیدها · دست‌کم ۱۰ ثانیه فعال، ۲ صفحه یا یک کار مهم",
        visits: "کل بازدیدها",
        visitsHint: "صفحه‌هایی که کمتر از ۳۰ دقیقه فاصله دارن یک بازدیدن",
        visitors: "بازدیدکننده · این ماه",
        visitorsHint: "آدم‌های جداگانه در همین ماه میلادی",
        returning: "برگشتی · این ماه",
        returningHint: "کسایی که این ماه دست‌کم ۲ بار اومدن",
        avgTime: "میانگین زمان فعال",
        avgTimeHint: "برای هر بازدید با تعامل؛ زمان بی‌کاری و تب پنهان حساب نمی‌شه",
        pagesPerVisit: "صفحه در هر بازدید",
        pagesPerVisitHint: "بازدید صفحه ÷ بازدیدها، در همون روزها",
        chat: "سؤال‌های چت",
        chatHint: "از دستیار پرسیده شده",
        contact: "پیام‌های تماس",
        contactHint: "از طریق فرم فرستاده شده",
      },
      trend: "بازدید در هر روز",
      allVisits: "همهٔ بازدیدها",
      engaged: "با تعامل",
      peak: "بیشترین",
      pageviews: "بازدید صفحه در این بازه",
      timeTitle: "زمان فعال در هر بازدید",
      buckets: [
        "کمتر از ۱۰ ثانیه",
        "۱۰ تا ۳۰ ثانیه",
        "۳۰ ثانیه تا ۱ دقیقه",
        "۱ تا ۳ دقیقه",
        "۳ تا ۱۰ دقیقه",
        "بیشتر از ۱۰ دقیقه",
      ],
      pagesTitle: "صفحه‌ها بر اساس میانگین زمان فعال",
      views: "بازدید",
      sectionsTitle: "بازدیدکننده‌ها تا کجا جلو می‌رن",
      sectionsHint:
        "دسترسی = سهم بازدیدهایی که اون صفحه رو باز کردن و بخش حدود یک ثانیه جلوی چشمشون بوده. میانگین = چقدر اون بخش اصلی‌ترین چیز روی صفحه بوده.",
      homeSections: "صفحهٔ اصلی",
      otherSections: "صفحه‌های دیگه",
      sectionNames: {
        hero: "بخش اول · چت",
        featured: "پروژه‌های منتخب",
        workplace: "ایجنت‌های کاری",
        about: "دربارهٔ من",
        contact: "تماس",
        "projects-list": "فهرست پروژه‌ها",
        "workplace-detail": "ایجنت‌های کاری با جزئیات",
        "case-study": "صفحه‌های پروژه",
      },
      avg: "میانگین",
      doTitle: "بازدیدکننده‌ها چی کار کردن",
      chatAsked: "سؤال‌های چت",
      chip: "سؤال پیشنهادی",
      typed: "سؤال تایپ‌شده",
      outcomesTitle: "نتیجهٔ سؤال‌های چت",
      outcomes: {
        answered: "جواب داده شد",
        cached: "جواب از حافظه",
        refused: "رد شد: بی‌ربط یا سوءاستفاده",
        smalltalk: "احوال‌پرسی",
        capped: "سقف روزانه پر شد",
        error: "خطا",
      },
      topicsTitle: "موضوع سؤال‌های چت",
      actionsTitle: "کارها",
      events: {
        chat_ask: "سؤال چت",
        contact_submit: "پیام تماس",
        resume_download: "دانلود رزومه",
        outbound: "لینک بیرونی",
        gallery_open: "باز کردن گالری",
        palette_open: "پالت فرمان",
        lang_switch: "تغییر زبان",
      },
      outboundTitle: "لینک‌های بیرونی",
      targets: {
        github: "پروفایل GitHub",
        repo: "مخزن پروژه",
        linkedin: "LinkedIn",
        email: "ایمیل",
        telegram: "تلگرام",
      },
      acqTitle: "بازدیدها از کجا میان",
      acqHint:
        "برای هر بازدید یک بار شمرده می‌شن. ماه‌به‌ماه ذخیره می‌شن، پس کل این ماه‌ها رو پوشش می‌دن:",
      sources: "منبع ورود",
      entryPages: "صفحهٔ ورود",
      countries: "کشورها",
      cities: "شهرها",
      devices: "دستگاه‌ها",
      browsers: "مرورگرها",
      languages: "زبان",
      langNames: { en: "انگلیسی", fa: "فارسی" },
      direct: "مستقیم",
      deviceNames: { Desktop: "دسکتاپ", Mobile: "موبایل", Tablet: "تبلت" },
      when: "زمان بازدید · به وقت خود بازدیدکننده‌ها",
      busiest: "شلوغ‌ترین ساعت: حدود",
      weekdays: { Mon: "د", Tue: "س", Wed: "چ", Thu: "پ", Fri: "ج", Sat: "ش", Sun: "ی" },
      recentTitle: "بازدیدهای اخیر",
      recentHint: "۵۰ بازدید آخر، جدیدترین اول",
      newVisitor: "جدید",
      returningVisitor: "برگشتی",
      engagedBadge: "با تعامل",
      active: "فعال",
      sec: " ثانیه",
      min: " دقیقه",
      unknown: "نامشخص",
      note: "برای بازدیدکننده‌ها cookie نداریم و IP خام هم نگه نمی‌داریم. شناسهٔ بازدیدکننده hash یک‌طرفهٔ IP و اطلاعات مرورگر با یک مقدار محرمانه‌ست که هر ماه عوض می‌شه؛ برای همین آمار بازدیدکننده و برگشتی فقط برای ماه جاریه. سابقهٔ هر بازدید ۹۰ روز می‌مونه.",
    },
  },
} as const;

export type PageCopy = (typeof pageCopy)[Locale];
